# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.3 on 2016-12-07 01:26
from __future__ import unicode_literals

import datetime
=======
# Generated by Django 1.10.3 on 2016-12-28 02:03
from __future__ import unicode_literals

>>>>>>> 257cf2374f6c5fd5c6d80d842109ee29cad5f3ee
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('own_room_num', models.IntegerField()),
                ('outdate_time', models.DateTimeField(default=datetime.datetime(2016, 12, 7, 9, 26, 16, 938278))),
            ],
        ),
=======
            name='IndexTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, unique=True)),
                ('own_room_num', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(default='', max_length=20)),
                ('addr', models.CharField(default='', max_length=200)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='indextable',
            name='interviewee_list',
            field=models.ManyToManyField(to='Account.Interviewee'),
        ),
>>>>>>> 257cf2374f6c5fd5c6d80d842109ee29cad5f3ee
    ]
