# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('own_room_num', models.IntegerField()),
                ('outdate_time', models.DateTimeField(default=datetime.datetime(2016, 12, 7, 9, 26, 16, 938278))),
            ],
        ),
    ]
