# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='outdate_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 28, 20, 52, 10, 335698)),
        ),
    ]
