# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20161207_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telephone', models.CharField(default='', max_length=20)),
                ('addr', models.CharField(default='', max_length=200)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='manager',
            name='outdate_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 14, 17, 9, 739261)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='own_room_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True),
        ),
    ]
