# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20161207_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='outdate_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 14, 18, 16, 94010)),
        ),
    ]
