# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20161207_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewee',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='manager',
            name='outdate_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 14, 37, 59, 292176)),
        ),
    ]
