# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_auto_20161207_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='outdate_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 15, 0, 17, 474273)),
        ),
    ]
