# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_auto_20161207_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewee',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='manager',
            name='outdate_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 15, 21, 37, 696751)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
