# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_auto_20161207_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='outdate_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 23, 20, 54, 21, 610221)),
        ),
    ]
