# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_auto_20161223_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='outdate_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 27, 22, 48, 43, 866293)),
        ),
    ]
