# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.3 on 2016-12-07 01:26
from __future__ import unicode_literals

from django.db import migrations, models
=======
# Generated by Django 1.10.3 on 2016-12-28 02:05
from __future__ import unicode_literals

import Account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 257cf2374f6c5fd5c6d80d842109ee29cad5f3ee


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 257cf2374f6c5fd5c6d80d842109ee29cad5f3ee
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('state', models.BooleanField()),
                ('manager', models.ManyToManyField(to='Account.Manager')),
=======
                ('title', models.CharField(default='Default room title', max_length=200)),
                ('description', models.CharField(default='Default description for a default room', max_length=1000)),
                ('state', models.BooleanField(default=False)),
                ('interviewees', models.ManyToManyField(to='Account.Interviewee')),
                ('interviewer', models.OneToOneField(default=Account.models.Interviewer(), on_delete=django.db.models.deletion.CASCADE, to='Account.Interviewer')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 257cf2374f6c5fd5c6d80d842109ee29cad5f3ee
            ],
        ),
    ]
