# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='port',
            field=models.IntegerField(default=8000, unique=True),
        ),
    ]
