# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='interviewer',
        ),
        migrations.AddField(
            model_name='room',
            name='interviewer_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
