# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:40
from __future__ import unicode_literals

import Account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20161207_1440'),
        ('Room', '0002_auto_20161207_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='manager',
            field=models.ForeignKey(default=Account.models.Manager(), on_delete=django.db.models.deletion.CASCADE, to='Account.Manager'),
        ),
    ]
