# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_auto_20161207_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Manager'),
        ),
    ]
