# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_auto_20161207_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='url',
            field=models.CharField(default='/room/usr/index', max_length=200),
        ),
    ]
