# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 07:00
from __future__ import unicode_literals

import Account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_auto_20161207_1500'),
        ('Room', '0006_auto_20161207_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='interviewees',
            field=models.ManyToManyField(to='Account.Interviewee'),
        ),
        migrations.AddField(
            model_name='room',
            name='interviewer',
            field=models.OneToOneField(default=Account.models.Interviewer(), on_delete=django.db.models.deletion.CASCADE, to='Account.Interviewer'),
        ),
    ]
