# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_auto_20161207_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
