# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_auto_20161207_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.Manager'),
        ),
    ]
